Remove Example
alexhagiopol/ctci pull request #81
Opened 2020-08-14 01:15 UTC by Vipul97

Example used here was irrelevant as it was from the previous question.

2020-09-06 21:08 UTC, alexhagiopol requested changes
Thanks for finding this mistake. However, we don't want to just remove the incorrect example. We want to remove the incorrect example and replace it with a correct example. For example:
```
Example:
Input: ("A" -> "B" -> "B"->"A")
Output: True
```

If you update your PR with a correct example, I will accept and merge.

2020-09-07 08:35 UTC, Vipul97 commented
Hi @alexhagiopol,

Thanks for your response!
I have updated the example on both Python and C++ version of the problem. Hope this will suffice.

2020-09-07 21:45 UTC, alexhagiopol commented
@Vipul97 Thanks for the contribution. I will merge it.

2020-09-07 21:45 UTC, alexhagiopol approved these changes

2020-09-07 21:46 UTC, merged